# -*- coding: utf-8 -*-
"""Carnival.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vhPeOTJxxW6mDerELmCf9iK6E6Csfk3I
"""

import pandas as pd
import numpy as np
train = pd.read_csv('/content/train.csv')
test = pd.read_csv('/content/test.csv')
train = train.drop(['Customer_name','Stall_no'], axis=1)
test = test.drop(['Customer_name', 'Stall_no'], axis=1)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
train['Loyalty_customer'] = label_encoder.fit_transform(train['Loyalty_customer'])
test['Loyalty_customer'] = label_encoder.transform(test['Loyalty_customer'])
train['Product_Category'] = label_encoder.fit_transform(train['Product_Category'])
test['Product_Category'] = label_encoder.transform(test['Product_Category'])
train['Selling_Price'] = label_encoder.fit_transform(train['Selling_Price'])

train['Product_Category'].unique()

train['instock_date'] = pd.to_datetime(train.instock_date, format='%Y-%m-%d %H:%M:%S')
train = train.assign(hour=train.instock_date.dt.hour,
               day=train.instock_date.dt.day,
               month=train.instock_date.dt.month,
               year=train.instock_date.dt.year)
train.head()
train = train.drop(['instock_date'],axis = 1)

test['instock_date'] = pd.to_datetime(test.instock_date, format='%Y-%m-%d %H:%M:%S')
test = test.assign(hour=test.instock_date.dt.hour,
               day=test.instock_date.dt.day,
               month=test.instock_date.dt.month,
               year=test.instock_date.dt.year)
test.head()
test = test.drop(['instock_date'],axis = 1)

train

test.info()

from sklearn.impute import SimpleImputer
final_imputer = SimpleImputer(strategy='most_frequent')
final_train = pd.DataFrame(final_imputer.fit_transform(train))
final_train.columns = train.columns

final_train.info()

train_y = final_train['Selling_Price']

train_x = final_train.drop(['Selling_Price','Product_id'],axis=1)
train_x.head()

from sklearn.ensemble import RandomForestRegressor 
regressor = RandomForestRegressor(random_state = 1)

regressor = regressor.fit(train_x, train_y)

from sklearn.impute import SimpleImputer
final_imputer = SimpleImputer(strategy='most_frequent')
final_test = pd.DataFrame(final_imputer.fit_transform(test))
final_test.columns = test.columns
final_test.info()

id = final_test['Product_id']

final_test = final_test.drop(['Product_id'],axis=1)

pred1 = regressor.predict(final_test)

final_test['Product_id'] = id

final_test['Selling_Price']=pred1

final_test

final_test = final_test.drop(['Market_Category','Loyalty_customer','Product_Category','Grade','Demand','Discount_avail','charges_1','charges_2 (%)','Minimum_price','Maximum_price','hour','day','month','year'],axis=1)

final_test

final_test.to_csv('ans5.csv')